### ISSUE TITLE
I can't find for scss

### ISSUE THREAD

**Issue by dael** [wilwaldon/flatstrap#56]
scss folder can not be found.
How can I use the scss?
thx for help

**Comment by ruchevits** [comment]
+1, http://zerox.me/projects/flatstrap/css/#sass links to this repo, but there seems to be no SASS version

**Comment by izer0x** [comment]
yes it's not available at the moment but soon it will be :)

**Comment by wilwaldon** [comment]
As Bootstrap 4 is just around the corner, this edition of Flatstrap will be set into maintenance mode so there will be no scss in the future. I am moving all my future development time and resources to Flatstrap 4.
